[general]
import = [
	"~/.config/alacritty/themes/ayu_mirage.toml"
]

live_config_reload = true

[window.dimensions]
columns=100
lines=30

[font]
size = 22.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.8
blur=true
decorations = "full"


